name: curtail
base: core22
adopt-info: curtail
summary: Curtail is an useful image compressor.
description: |
  Curtail is an useful image compressor, supporting PNG, JPEG, WebP and SVG file types.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64

slots:
  curtail:
    interface: dbus
    bus: session
    name: io.github.CapeCrusader321.curtail

apps:
  curtail:
    command: usr/bin/curtail
    extensions: [gnome]
    common-id: snap.curtail.community
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - network-status
      - network
      - network-bind
      - raw-usb
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  curtail:
    source: https://github.com/Huluti/Curtail.git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
     
     
   
    
   
