name: curtail
base: core22
adopt-info: curtail
version: 1.7.0
grade: stable
confinement: strict
compression: lzo
icon: snap/gui/curtail.svg
architectures:
  - build-on: amd64
    build-for: amd64

#plugs:
  #curtail:
    #interface: dbus
    #bus: session
    #name: com.github.huluti.Curtail

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH

apps:
  curtail:
    command: usr/bin/curtail
    extensions: [gnome]
    desktop: usr/share/applications/com.github.huluti.Curtail.desktop
    plugs:
      - home
      - removable-media
parts:
  libadwaita:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/libadwaita/-/archive/1.3.1/libadwaita-1.3.1.tar.bz2
    override-pull: |
      craftctl default
      # WORKAROUND: Ignore compiler warning
      sed -e 's/-W\(format-nonliteral\)\b/-Wno-\1/g' -i meson.build

    prime:
      - usr/lib/*/*adw*
      - usr/lib/*/*/Adw*

    meson-parameters:
      - --prefix=/usr
      - -Dexamples=false
      - -Dtests=false
      - -Dintrospection=enabled
      - -Dvapi=false
    stage:
      - -usr/include
      
    #meson-parameters:
      #- --prefix=/usr
      #- -Doptimization=3
      #- -Ddebug=true
      #- -Dintrospection=enabled
      #- -Dvapi=true
      #- -Dtests=false
      #- -Dexamples=false
   

  curtail:
    after: [oxipng, libadwaita]
    source: https://github.com/Huluti/Curtail.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: meson
    meson-parameters:
      - --prefix=/snap/curtail/current/usr
    stage-packages:
      - pngquant
      - scour
      - jpegoptim
    override-pull: |
      craftctl default
      sed -e 's|Icon=com.github.huluti.Curtail|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.huluti.Curtail.svg|' -i data/com.github.huluti.Curtail.desktop.in
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/curtail/current/usr/bin/curtail
    organize:
      snap/curtail/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.huluti.Curtail.appdata.xml]
  oxipng:
    source: https://github.com/shssoichiro/oxipng.git
    plugin: rust
    build-packages:
      - cargo
