name: curtail
base: core22
adopt-info: curtail
summary: Curtail is an useful image compressor, supporting PNG, JPEG, WebP and SVG file types. 
description: |
  Curtail (previously ImCompressor) is an useful image compressor, supporting PNG, JPEG, WebP and SVG file types. It support both lossless and lossy compression modes with an option to whether keep or not metadata of images. It is inspired by Trimage and Image-Optimizer.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64

slots:
  curtail:
    interface: dbus
    bus: session
    name: io.github.CapeCrusader321.curtail

apps:
  curtail:
    command: usr/bin/curtail
    extensions: [gnome]
    common-id: snap.community.curtail
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - network-status
      - network
      - network-bind
      - raw-usb
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  curtail:
    source: https://github.com/Huluti/Curtail.git
    plugin: meson
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
     
     
   
    
   
